Jding/patch701 tps 3441 (#4069)
* fix(TUP-24540)java.lang.NoSuchMethodError: (#3978) (#3999)

org.slf4j.spi.LocationAwareLogger.log
https://jira.talendforge.org/browse/TUP-24540

Conflicts:
	main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java
	test/plugins/org.talend.designer.core.test/src/org/talend/designer/core/utils/JavaProcessUtilTest.java

Conflicts:
	main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java

* fix(TUP-24540)java.lang.NoSuchMethodError: (#4018) (#4021)

org.slf4j.spi.LocationAwareLogger.log
https://jira.talendforge.org/browse/TUP-24540

* fix(TUP-24540)java.lang.NoSuchMethodError: (#4055)

org.slf4j.spi.LocationAwareLogger.log
https://jira.talendforge.org/browse/TUP-24540

Conflicts:
	main/plugins/org.talend.designer.core/src/main/java/org/talend/designer/core/utils/JavaProcessUtil.java